<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Smartreport_hotels_model extends CI_Model
{


    function __construct()
    {
        parent::__construct();
    }

    // get all
    public function insertData($table,$data)
    {
        $this->db->insert($table, $data);
    }  

    // Query Data from Table with Order;
    public function getDataAll($table, $order_column, $order_type){
        $this->db->order_by("$order_column", "$order_type");
        $query = $this->db->get("$table");
        $result = $query->result();
        $this->db->save_queries = false;
        return $result;
    }
    public function getDataParent($table, $order_column, $parent, $order_type ){
        $this->db->where('parent', $parent);
        $this->db->order_by("$order_column", "$order_type");
        $query = $this->db->get("$table");
        $result = $query->result();
        $this->db->save_queries = false;
        return $result;
    }

    // get total rows
    function total_rows_hotels($q = NULL) {
        $this->db->select('h.idhotels, h.idcity, c.city_name, h.parent, h.hotels_name, h.total_rooms, h.hotel_star, h.status, h.date_created');       
        $this->db->from('smartreport_hotels as h');
        $this->db->join('smartreport_city as c', 'h.idcity=c.idcity','left');
        if ($q !== NULL){
            $this->db->like('h.hotels_name', $q);
        } 
        $this->db->where('parent', 'PARENT');
        $this->db->order_by('h.hotels_name', 'ASC');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_hotels($limit, $start = 0, $q = NULL) {
        $this->db->select('h.idhotels, h.idcity, c.city_name, h.parent, h.hotels_name, h.total_rooms, h.hotel_star, h.status, h.date_created');       
        $this->db->from('smartreport_hotels as h');
        $this->db->join('smartreport_city as c', 'h.idcity=c.idcity','left');
        if ($q !== NULL){
            $this->db->like('h.hotels_name', $q);
        } 
        $this->db->where('parent', 'PARENT');
        $this->db->order_by('h.hotels_name', 'ASC');
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // update data
    public function updateDataHotels($table, $data, $idhotels_old)
    {
        $this->db->where('idhotels', $idhotels_old);
        $this->db->update("$table", $data);

        return true;
    }

    function deleteDataHotels($idhotels)
    {
        $this->db->where('idhotels', $idhotels);
        $this->db->delete('smartreport_hotels');
    }

        // get total rows
    function total_rows_competitor($competitor = NULL, $city = NULL, $listhotel = NULL) {
        $this->db->select('h1.idhotels as idcompetitor, h.idhotels, h1.idcity, c.city_name, h.hotels_name, h1.hotels_name as competitor, h1.total_rooms, h1.hotel_star, h1.status, h1.date_created');       
        $this->db->from('smartreport_hotels as h');        
        $this->db->join('smartreport_hotels as h1', 'h.idhotels=h1.parent','left');
        $this->db->join('smartreport_city as c', 'h1.idcity=c.idcity','left');
        if($city !== 'all'){
            $this->db->like('h1.idcity', $city);
        }
        if($listhotel !== 'all'){
            $this->db->like('h.idhotels', $listhotel);
        }
        if ($competitor !== NULL){
            $this->db->like('h1.hotels_name', $competitor);
        } 
        $this->db->where('h1.parent !=', 'PARENT');
        $this->db->order_by('h1.hotels_name', 'ASC');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_competitor($limit, $start = 0, $competitor = NULL, $city = NULL, $listhotel = NULL) {
        $this->db->select('h1.idhotels as idcompetitor, h.idhotels, h1.idcity, c.city_name,  h.hotels_name, h1.hotels_name as competitor, h1.total_rooms, h1.hotel_star, h1.status, h1.date_created');       
        $this->db->from('smartreport_hotels as h');
              
        $this->db->join('smartreport_hotels as h1', 'h.idhotels=h1.parent','left');
        $this->db->join('smartreport_city as c', 'h1.idcity=c.idcity','left');  
        if($city !== 'all'){
            $this->db->like('h1.idcity', $city);
        }
        if($listhotel !== 'all'){
            $this->db->like('h.idhotels', $listhotel);
        }
        if ($competitor !== NULL){
            $this->db->like('h1.hotels_name', $competitor);
        } 
        $this->db->where('h1.parent !=', 'PARENT');
        $this->db->order_by('h1.hotels_name', 'ASC');
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

}

/* End of file smartreport_hotels_model.php */
/* Location: ./application/models/smartreport_hotels_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-06 09:54:09 */
/* http://harviacode.com */